### ISSUE TITLE
 Unable to find package libpjsua2.maui.android

### ISSUE THREAD

**Issue by lonelyxmas** [weslleymurdock/pjsua2maui#2]
vs 17.9.0 preview  : 
Unable to find package libpjsua2.maui.android. No packages exist with this id in source(s): Microsoft Visual Studio Offline Packages, nuget.org, voip
System.InvalidOperationException: Unable to find metadata of libpjsua2.maui.android

**Comment by weslleymurdock** [comment]
Hi
You can post the steps that gave the following issue?

**Comment by weslleymurdock** [comment]
Im currently changing the structure of the packages; later release.
If you could help test, i'll  be gratefull
